FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake

COPY . /repo
WORKDIR /repo/cmake/build
RUN cmake ..
RUN make -j8

FROM ubuntu:22.04 as package
COPY --from=builder /repo/cmake/build/verovio /
